version: '3.8'

services:
  # Bot Service (Python)
  bot-service:
    build: 
      context: ./bot-service
      dockerfile: Dockerfile
    container_name: expense_bot_service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      BOT_SERVICE_HOST: 0.0.0.0
      BOT_SERVICE_PORT: 8000
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./bot-service/logs:/app/logs
    network_mode: "host"

  # Connector Service (Node.js)
  connector-service:
    build:
      context: ./connector-service
      dockerfile: Dockerfile
    container_name: expense_connector_service
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      WEBHOOK_URL: ${WEBHOOK_URL}
      BOT_SERVICE_URL: http://localhost:8000
      PORT: 3000
      NODE_ENV: production
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - bot-service
    restart: unless-stopped
    volumes:
      - ./connector-service/logs:/app/logs
    network_mode: "host" 